<a href="https://colab.research.google.com/github/markajbell/BH/blob/main/Stats_all.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import pandas as pd
import json

# Load the JSON files
with open('vul1k_nodes.json', 'r') as f:
    vul1k_data = json.load(f)

with open('vul5k_nodes.json', 'r') as f:
    vul5k_data = json.load(f)

with open('secure1k_nodes.json', 'r') as f:
    sec1k_data = json.load(f)

with open('secure10k_nodes.json', 'r') as f:
    sec10k_data = json.load(f)

with open('secure50k_nodes.json', 'r') as f:
    sec50k_data = json.load(f)


# Convert JSON data to DataFrames
df_vul1k = pd.DataFrame(list(vul1k_data.items()), columns=['Label', 'vul1k'])
df_vul5k = pd.DataFrame(list(vul5k_data.items()), columns=['Label', 'vul5k'])
df_sec1k = pd.DataFrame(list(sec1k_data.items()), columns=['Label', 'sec1k'])
df_sec10k = pd.DataFrame(list(sec10k_data.items()), columns=['Label', 'sec10k'])
df_sec50k = pd.DataFrame(list(sec50k_data.items()), columns=['Label', 'sec50k'])
#df_vul5k = pd.DataFrame(list(vul5k_data.items()), columns=['Label', 'vul5k'])

# Merge the DataFrames on the 'Label' column
merged_df = pd.merge(df_vul1k, df_vul5k, on='Label', how='outer')
merged_df = pd.merge(merged_df, df_sec1k, on='Label', how='outer')
merged_df = pd.merge(merged_df, df_sec10k, on='Label', how='outer')
merged_df = pd.merge(merged_df, df_sec50k, on='Label', how='outer').fillna(0)


# Sort the DataFrame by 'vul1k_Count' in ascending order
merged_df_sorted = merged_df.sort_values(by='vul1k', ascending=True)

# Display the sorted DataFrame
display(merged_df_sorted)

       Label  vul1k  vul5k  sec1k  sec10k  sec50k
0     ALL_T0      1      1      1       1       1
2  Container      1      1      1       1       1
3     Domain      1      1      1       1       1
4        GPO     41     41    181      41      41
6         OU     48     48     44      48      48
5      Group    202   1769    656    3370    8181
1   Computer    309   1609    209    3309   25009
7       User    505   1805    205    3305   15005

In [ ]:
import json
import pandas as pd

# Load the JSON files
with open('vul1k_label.json', 'r') as f:
    vul1k_label_data = json.load(f)

with open('vul5k_label.json', 'r') as f:
    vul5k_label_data = json.load(f)

# Convert JSON data to DataFrames
df_vul1k_label = pd.DataFrame(list(vul1k_label_data.items()), columns=['Label', 'vul1k_Label_Count'])
df_vul5k_label = pd.DataFrame(list(vul5k_label_data.items()), columns=['Label', 'vul5k_Label_Count'])

# Merge the DataFrames on the 'Label' column
merged_label_df = pd.merge(df_vul1k_label, df_vul5k_label, on='Label', how='outer').fillna(0)

# Sort the DataFrame by 'vul1k_Label_Count' in ascending order
merged_label_df_sorted = merged_label_df.sort_values(by='vul1k_Label_Count', ascending=True)

# Display the merged and sorted DataFrame
display(merged_label_df_sorted)

                  Label  vul1k_Label_Count  vul5k_Label_Count
14        GetChangesAll                  2                  2
13           GetChanges                  3                  3
0             AddMember                  6                  3
18                 Owns                  6                  6
10  ForceChangePassword                  8                  7
20             SQLAdmin                 12                121
1               AddSelf                 15                 11
4          AllowedToAct                 16                123
6           CanPSRemote                 18                110
7                CanRDP                 20                136
9           ExecuteDCOM                 22                149
19     ReadLAPSPassword                 23                115
5     AllowedToDelegate                 26                142
3     AllExtendedRights                 26                 30
15               GpLink                 42                 42
2               AdminTo                 46                164
21                TIER0                 72                265
12         GenericWrite                 99                105
22            WriteDacl                105                105
23           WriteOwner                108                102
16           HasSession                149               9423
11           GenericAll                168                172
8              Contains               1064               5231
17             MemberOf               5097              12015

In [11]:
# Save the merged and sorted DataFrame to a JSON file
merged_df_sorted.to_json('all_nodes.json', orient='records', indent=4)

print("merged_df_sorted saved to all_nodes.json")

merged_df_sorted saved to all_nodes.json

In [12]:
import pandas as pd
import json

# Load the JSON files
with open('vul1k_label.json', 'r') as f:
    vul1k_data = json.load(f)

with open('vul5k_label.json', 'r') as f:
    vul5k_data = json.load(f)

with open('secure1k_label.json', 'r') as f:
    sec1k_data = json.load(f)

with open('secure10k_label.json', 'r') as f:
    sec10k_data = json.load(f)

with open('secure50k_label.json', 'r') as f:
    sec50k_data = json.load(f)


# Convert JSON data to DataFrames
df_vul1k = pd.DataFrame(list(vul1k_data.items()), columns=['Label', 'vul1k_label'])
df_vul5k = pd.DataFrame(list(vul5k_data.items()), columns=['Label', 'vul5k_label'])
df_sec1k = pd.DataFrame(list(sec1k_data.items()), columns=['Label', 'sec1k_label'])
df_sec10k = pd.DataFrame(list(sec10k_data.items()), columns=['Label', 'sec10k_label'])
df_sec50k = pd.DataFrame(list(sec50k_data.items()), columns=['Label', 'sec50k_label'])


# Merge the DataFrames on the 'Label' column
merged_df = pd.merge(df_vul1k, df_vul5k, on='Label', how='outer')
merged_df = pd.merge(merged_df, df_sec1k, on='Label', how='outer')
merged_df = pd.merge(merged_df, df_sec10k, on='Label', how='outer')
merged_df = pd.merge(merged_df, df_sec50k, on='Label', how='outer').fillna(0)


# Sort the DataFrame by 'vul1k_label' in ascending order
merged_df_sorted = merged_df.sort_values(by='vul1k_label', ascending=True)

# Display the sorted DataFrame
display(merged_df_sorted)

,Label,vul1k_label,vul5k_label,sec1k_label,sec10k_label,sec50k_label
5,"AllowedToDe,legate",0.0,0.0,0.0,0.0,2.0
15,GetChangesAll,2.0,2.0,2.0,2.0,2.0
14,GetChanges,3.0,3.0,3.0,3.0,3.0
0,AddMember,6.0,3.0,14.0,11.0,11.0
19,Owns,6.0,6.0,53.0,6.0,6.0
11,ForceChangePassword,8.0,7.0,15.0,8.0,10.0
21,SQLAdmin,12.0,121.0,0.0,0.0,0.0
1,AddSelf,15.0,11.0,13.0,3.0,8.0
4,AllowedToAct,16.0,123.0,0.0,4.0,2.0
7,CanPSRemote,18.0,110.0,0.0,1.0,1.0
8,CanRDP,20.0,136.0,3.0,4.0,5.0
10,ExecuteDCOM,22.0,149.0,1.0,4.0,5.0
20,ReadLAPSPassword,23.0,115.0,1.0,1.0,5.0
3,AllExtendedRights,26.0,30.0,28.0,25.0,26.0
6,AllowedToDelegate,26.0,142.0,0.0,4.0,2.0
16,GpLink,42.0,42.0,182.0,42.0,42.0
2,AdminTo,46.0,164.0,30.0,31.0,26.0
22,TIER0,72.0,265.0,52.0,527.0,2669.0
13,GenericWrite,99.0,105.0,105.0,99.0,103.0
23,WriteDacl,105.0,105.0,108.0,109.0,104.0
24,WriteOwner,108.0,102.0,105.0,109.0,104.0
17,HasSession,149.0,9423.0,662.0,16144.0,86555.0
12,GenericAll,168.0,172.0,171.0,172.0,168.0
9,Contains,1064.0,5231.0,1254.0,10032.0,48243.0
18,MemberOf,5097.0,12015.0,1224.0,21507.0,100235.0

In [13]:
# Save the merged and sorted DataFrame to a JSON file
merged_df_sorted.to_json('all_label.json', orient='records', indent=4)

print("merged_df_sorted saved to all_nodes.json")

merged_df_sorted saved to all_nodes.json